name: Morning Weather Notification

on:
  schedule:
    - cron: "*/5 * * * *"  # 日本時間17:00（UTC 8:00）
  workflow_dispatch:

jobs:
  run-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          PUSHBULLET_API_KEY: ${{ secrets.PUSHBULLET_API_KEY }}
        run: python weather.py
